# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-05 07:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20171105_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutme',
            name='subheading',
        ),
    ]
