# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-05 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_aboutme_subheading'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='subheading',
            field=models.CharField(blank=True, max_length=70),
        ),
    ]
